name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"

    - name: Wait for AI analysis
      run: |
        echo "Waiting for AI analysis to complete..."
        sleep 30  # Give AI workflow time to run
        
        # Check if AI approved
        labels=$(gh pr view ${{ github.event.pull_request.number }} --json labels -q '.labels[].name' | tr '\n' ' ')
        
        if echo "$labels" | grep -q "needs-review"; then
          echo "::warning::AI analysis found concerns - manual review required"
          exit 0  # Don't fail, just skip auto-merge
        fi
        
        if echo "$labels" | grep -q "ai-approved"; then
          echo "✅ AI analysis approved this update"
        fi
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Auto-merge minor and patch updates
      if: steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'
      run: |
        # Only auto-merge if not flagged by AI
        labels=$(gh pr view ${{ github.event.pull_request.number }} --json labels -q '.labels[].name' | tr '\n' ' ')
        
        if echo "$labels" | grep -q "needs-review"; then
          echo "Skipping auto-merge due to AI concerns"
        else
          gh pr merge --auto --merge "$PR_URL"
        fi
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Auto-approve minor and patch updates
      if: steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'
      run: gh pr review --approve "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Comment on major updates
      if: steps.metadata.outputs.update-type == 'version-update:semver-major'
      run: |
        gh pr comment "$PR_URL" --body "⚠️ **Major version update detected!**
        
        This PR contains a major version update and requires manual review.
        
        Package: ${{ steps.metadata.outputs.dependency-names }}
        Update: ${{ steps.metadata.outputs.previous-version }} → ${{ steps.metadata.outputs.new-version }}
        
        Please review breaking changes before merging."
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}